name: Graph API Intune Automation
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write   # Required for OIDC authentication
  contents: read

jobs:
  call-graph-api:
    runs-on: ubuntu-latest
    environment: GraphApi
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true
