name: Graph API Intune Automation
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write   # Required for OIDC authentication
  contents: read

jobs:
  call-graph-api:
    runs-on: ubuntu-latest
    environment: GraphApi
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Request GitHub OIDC Token
        id: get-oidc-token
        uses: actions/github-script@v7
        with:
          script: |
            const response = await github.rest.actions.createOidcToken({});
            console.log("OIDC Token obtained");
            return response.data.value;

      - name: Exchange OIDC Token for Entra ID Token
        id: get-entra-token
        run: |
          OIDC_TOKEN="${{ steps.get-oidc-token.outputs.result }}"
          
          RESPONSE=$(curl -s -X POST "https://login.microsoftonline.com/${{ secrets.AZURE_TENANT_ID }}/oauth2/v2.0/token" \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "client_id=${{ secrets.AZURE_CLIENT_ID }}" \
          -d "client_assertion=$OIDC_TOKEN" \
          -d "client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer" \
          -d "grant_type=client_credentials" \
          -d "scope=https://graph.microsoft.com/.default")

          GRAPH_TOKEN=$(echo $RESPONSE | jq -r .access_token)
          echo "::add-mask::$GRAPH_TOKEN"
          echo "GRAPH_TOKEN=$GRAPH_TOKEN" >> $GITHUB_ENV

      - name: Use Graph API Token
        run: |
          echo "Token retrieved successfully."
          curl -s -X GET "https://graph.microsoft.com/v1.0/me" \
          -H "Authorization: Bearer $GRAPH_TOKEN" \
          -H "Content-Type: application/json"
